moth:
  image: andresriancho/django-moth:latest
  ports:
    - "8000:8000"
    - "8001:8001"


wivet:
  image: andresriancho/wivet:latest
  ports:
    - "8899:80"


php-moth:
  image: andresriancho/php-moth:latest
  ports:
    - "9009:80"
